export const Endpoints = {
  REGISTER: "register",
  LOGIN: "login",
  SEND_OTP: "sendOTP",
  VERIFY_OTP: "verifyOtp",
  RESET_PASSWORD: "resetPassword",
  CHECK_CREDENTIALS: "checkCredentials",
  SHOW_FAQ: "showFAQ",
  NOTIFICATION_CALLBACK: "notificationCallBack",
  GET_ALL_CITIES: "getAllCities",
  GET_MY_PROFILE_DETAILS: "getMyProfileDetails",

  LOGOUT: "logout",

  PLACE_ORDER: "placeOrder",
  BOOKINGS_AGAINST_STATUS: "bookingsAgainstStatus",
  SHOW_ALL_COMPLETED_BOOKINGS: "showAllCompletedBookings",
  SHOW_ALL_CANCELED_BOOKINGS: "showAllCanceledBookings",
  BOOKINGS_UPCOMING: "bookings/upcoming",
  UPDATE_BOOKING_STATUS: "bookings/{booking}/status",
  SHOW_ACTIVE_BOOKINGS: "showActiveBookings",
  MARK_AS_CANCELLED: "markAsCancelled",
  MARK_AS_START: "markAsStart",
  MARK_AS_COMPLETED: "markAsCompleted",

  WORKERS: "workers",
  WORKER_DETAILS: "workerdetails",
  SHOW_ALL_WORKER_PROFILE: "showAllWorkerProfile",
  SET_WORKER_STATUS: "setWorkerStatus",
  UPDATE_LOCATION: "updateLocation",
  CHECK_ONLINE_WORKERS: "checkOnlineWorkers",
  GET_WORKER_ANALYTIC: "getWorkerAnalytic",
  GET_WORKER_BOOKING_COUNT_MONTH: "getWorkerBookingCountMonth",
  GET_WORKER_WITHDRAWL: "getWorkerWithdrawl",
  GET_WORKER_STATUS: "getWorkerStatus",

  ADD_NEW_SERVICE: "addNewService",
  SHOW_MY_SERVICES: "showMyServices",
  EDIT_MY_SERVICES: "editMyServices",
  DELETE_SERVICE_IMAGES: "deleteServiceImages",
  DELETE_MY_SERVICES: "deleteMyServices",
  SERVICES_POPULAR: "services/popular",
  SERVICES_POPULAR_AGAINST_CATEGORY: "services/popularAgainstCategory",
  SERVICES_AGAINST_CATEGORY: "servicesAgainstCategory",
  GET_SEARCH: "getSearch",
  SEARCH_ALL: "searchAll",
  GET_SEARCH_HISTORY: "getSearchHistory",
  GET_SERVICES: "getServices",
  GET_SERVICE_DETAIL: "getServiceDetail",
  GET_WORKER_MULTIPLE_SERVICES: "getWorkerMultipleServices",

  GET_ALL_CATEGORIES: "getAllCategories",
  GET_CATEGORY_DETAILS: "getCategoryDetails",

  BIDS: "bids",
  SHOW_PLACE_BIDS_CUSTOMERS: "showPlaceBidsCustomers",
  BID_CREATION_CUSTOMER: "bidCreationCustomer",
  SHOW_OPEN_BIDS: "showOpenBids",
  GET_BID_DETAILS: "getBidDetails",
  GET_BOOKING_DETAILS: "getBookingDetails",
  MARK_AS_TIMEOUT_CANCELLED: "markAsTimeOutCancelled",

  DIRECT_AS_WORKER: "directAsWorker",
  BID_RESPONSE_WORKER: "bidResponseWorker",

  SHOW_BID_RESPONSE_CUSTOMER: "showBidResponseCustomer",

  DIRECT_AS_CUSTOMER: "directAsCustomer",
  CANCELED_BID_CUSTOMER: "canceledBidCustomer",
  BID_AGAIN_OFFER_CUSTOMER: "bidAgainOfferCustomer",

  UPDATE_PROFILE: "updateProfile",
  CHANGE_PASSWORD: "changePassword",
  SHOW_PROFILE: "showProfile",

  CHECK_ACCOUNT_VERIFICATION: "checkAccountVerification",
  ADD_VERIFICATION_CNIC: "addVerificationCnic",
  ADD_VERIFICATION_LIVE_PHOTO: "addVerificationLivePhoto",
  ADD_VERIFICATION_PASSPORT: "addVerificationPassport",

  ADD_REVIEW: "addReview",
  EDIT_REVIEW: "editReview",
  DELETE_REVIEW: "deleteReview",
  GET_REVIEWS: "getReviews",

  SEND_FEEDBACK: "sendFeedback",

  SHOW_BOOKMARK: "showBookmark",
  ADD_BOOKMARK: "addbookmark",

  OFFERS: "offers",
  SHOW_SPECIAL_OFFERS: "showSpecialOffers",

  ADD_WORKER_AVAILABILITY: "addWorkerAvailability",
  GET_WORKER_AVAILABILITY: "getWorkerAvailability",
  GET_AVAILABLE_WORKERS_BY_MONTH: "getAvailableWorkersByMonth",
  GET_DIRECT_BOOKING_REQUEST: "getDirectBookingRequest",
  GET_BOOKINGS_BY_DATE: "getBookingsByDate",
  DIRECT_BOOKING_AS_WORKER: "directBookingAsWorker",
  GET_MONTH_WISE_BOOKINGS: "getMonthWiseBookings",
  GET_DAY_WISE_BOOKINGS: "getDayWiseBookings",

  SHOW_NOTIFICATIONS: "showNotifications",
  SHOW_CHAT_LIST: "showChatList",
  SEND_CHAT_NOTIFICATION: "sendChatNotification",
  CLEAR_ALL_NOTIFICATIONS: "clearAllNotifications",
  DELETE_NOTIFICATION: "deleteNotification",
  MARK_READ_NOTIFICATION: "markReadNotification",
  TEST_NOTIFICATIONS: "testNotifications",
  ADD_NOTIFICATION: "addNotification",
  UPDATE_TOKEN: "updateToken",

  SHOW_WORKER_TRANSACTION: "showWorkerTransaction",
  ADD_WORKER_TRANSACTION: "addWorkerTransaction",

  SHOW_CUSTOMER_TRANSACTION: "showCustomerTransaction",

  CALCULATE_CHARGES: "calculateCharges",
  SHOW_PAYMENT_HISTORY: "showPaymentHistory",
  SHOW_ALL_PAYMENT_METHODS: "showAllPaymentMethods", 
  SHOW_SAVED_PAYMENT_METHOD: "showSavedPaymentMethod",
  ADD_PAYMENT_METHOD: "addPaymentMethod",
  UPDATE_PAYMENT_METHOD: "updatePaymentMethod",
  DELETE_PAYMENT_METHOD: "deletePaymentMethod",
  INIT_PAYMENT_GATEWAY: "initPaymentGateway",
  SHOW_WALLET_CREDIT: "showWalletCredit",
  DEDUCT_BOOKING_AMOUNT: "deductBookingAmount",
  GET_PAYMENT_INFO: "getPaymentInfo",

  SHOW_SETTINGS: "showSettings",

  SWITCH_LANGUAGE: "language/{locale}",

  PRIVACY_POLICY: "https://buddy.site/privacy-policy.php",
  REFUND_POLICY: "https://buddy.site/refund-policy.php",
};